name=EepromToolsWithBytesBuffer
version=0.1.0
author=Tobias Knauss <tobias.knauss@web.de>
maintainer=Tobias Knauss <tobias.knauss@web.de>
sentence=Auxiliary methods for EEPROM, using the BytesBuffer library.
paragraph=Auxiliary methods for reading from and writing to EEPROM, from/to a BytesBuffer.
category=Other
url=https://github.com/TobiasKnauss/ArduinoLib_EepromToolsWithBytesBuffer
architectures=*
